import os


AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_LLM_DEPLOYMENT_NAME = os.getenv(
    "AZURE_OPENAI_LLM_DEPLOYMENT_NAME")
AZURE_OPENAI_SLM_DEPLOYMENT_NAME = os.getenv(
    "AZURE_OPENAI_SLM_DEPLOYMENT_NAME")
CONTENT_SAFETY_ENDPOINT = os.getenv("CONTENT_SAFETY_ENDPOINT")

USER_NAME = os.getenv("USER_NAME", "Ksenia Frank")
USER_ROLE = os.getenv("USER_ROLE", "Customer")
