import os


AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_LLM_DEPLOYMENT_NAME = os.getenv(
    "AZURE_OPENAI_LLM_DEPLOYMENT_NAME")
AZURE_OPENAI_SLM_DEPLOYMENT_NAME = os.getenv(
    "AZURE_OPENAI_SLM_DEPLOYMENT_NAME")
CONTENT_SAFETY_ENDPOINT = os.getenv("CONTENT_SAFETY_ENDPOINT")
AI_SEARCH_ENDPOINT = os.getenv("AI_SEARCH_ENDPOINT")
AI_SEARCH_INDEX_NAME = os.getenv("AI_SEARCH_INDEX_NAME")
EMBEDDING_MODEL_DEPLOYMENT_NAME = os.getenv("EMBEDDING_MODEL_DEPLOYMENT_NAME")

USER_NAME = os.getenv("USER_NAME", "Ksenia Frank")
USER_ROLE = os.getenv("USER_ROLE", "Customer")

WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")
WEATHER_API_URL = os.getenv("WEATHER_API_URL")
EXCHANGE_RATE_API_KEY = os.getenv("EXCHANGE_RATE_API_KEY")
EXCHANGE_RATE_API_URL = os.getenv("EXCHANGE_RATE_API_URL")
